services:
  web:
    git_url: git@github.com:MikeRogers0/MaestroDocker.git
    git_branch: master
    command: bundle exec rails s -b '0.0.0.0'
    build_command: /bin/sh -c "RAILS_ENV=_env:RAILS_ENV bundle exec rake db:schema:load"
    deploy_command: /bin/sh -c "RAILS_ENV=_env:RAILS_ENV bundle exec rake db:migrate"
    build_root: .
    ports:
      - container: 3000
        http: 80
        https: 443
    env_vars:
      PORT: 3000
      RAILS_ENV: production
      RACK_ENV: production
  worker:
    git_url: git@github.com:MikeRogers0/MaestroDocker.git
    git_branch: master
    command: bundle exec sidekiq
    build_root: .
    env_vars:
      RAILS_ENV: production
      RACK_ENV: production
