services:
  web:
    ports:
    - 3000:80
    git_url: git@github.com:MikeRogers0/MaestroDocker.git
    git_branch: master
    dockerfile_path: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    deploy_command: bundle exec rake db:migrate
databases: []
version: 2
